[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  TOML_ENV = "Production"

[context.branch-deploy.environment]
  TOML_ENV = "Branch Deploy"

[context.deploy-preview.environment]
  TOML_ENV = "Deploy Preview"