[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
TELEGRAM_BOT_TOKEN = "7921538449:AAG278ik-III5ynMuZ2zxprsC1BW0hDZGWw"