services:
  - type: web
    name: caderninho-bot-ia
    env: node
    buildCommand: npm install --production
    startCommand: node bot-ia.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SYSTEM_API_URL
        value: https://caderninhodigital.netlify.app
      - key: RENDER_EXTERNAL_URL
        sync: false