services:
  - type: web
    name: caderninho-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7921538449:AAG278ik-III5ynMuZ2zxprsC1BW0hDZGWw